image: ruby

pages:
  stage: build
  script:
  - gem install jekyll
  - gem install jekyll-seo-tag
  - gem install jekyll-sitemap
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master